# Generated by Django 5.2.1 on 2025-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('description', models.CharField(max_length=350, verbose_name='Описание фильма')),
                ('picture', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
