# Generated by Django 5.2.1 on 2025-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_films_options_alter_films_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
