# Generated by Django 5.2.1 on 2025-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_films_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
