# Generated by Django 5.2.1 on 2025-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_films_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на видео или файл'),
        ),
    ]
