# Generated by Django 5.2.1 on 2025-06-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tag_films_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Genre',
        ),
    ]
