# Generated by Django 5.2.1 on 2025-06-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_tag_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.RenameField(
            model_name='films',
            old_name='tags',
            new_name='genres',
        ),
    ]
